services:
  server:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      # ArkValut
      - DATABASE_URL=/app/data/database.sqlite
      - JWT_SECRET=${JWT_SECRET:?} # Required
      - JWT_ACCESS_TOKEN_EXPIRES
      - JWT_REFRESH_TOKEN_EXPIRES
      - PUBKEY_CHALLENGE_EXPIRES
      # SvelteKit
      - ADDRESS_HEADER=${TRUST_PROXY:+X-Forwarded-For}
      - XFF_DEPTH=${TRUST_PROXY:-}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - ${PORT:-80}:3000
