services:
  server:
    build: .
    restart: unless-stopped
    user: ${CONTAINER_UID:-0}:${CONTAINER_GID:-0}
    volumes:
      - ./data:/app/data
    environment:
      # ArkVault
      - DATABASE_URL=/app/data/database.sqlite
      - SESSION_SECRET=${SESSION_SECRET:?} # Required
      - SESSION_EXPIRES
      - USER_CLIENT_CHALLENGE_EXPIRES
      - SESSION_UPGRADE_CHALLENGE_EXPIRES
      - LIBRARY_PATH=/app/data/library
      # SvelteKit
      - ADDRESS_HEADER=${TRUST_PROXY:+X-Forwarded-For}
      - XFF_DEPTH=${TRUST_PROXY:-}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - ${PORT:-80}:3000
