services:
  database:
    image: postgres:17.2
    restart: on-failure
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?} # Required
      - POSTGRES_DB=${DATABASE_NAME:-}
    ports:
      - ${DATABASE_PORT:-5432}:5432

volumes:
  database:
